version: '3.6'
x-cache-from:
  - &app-cache-from
    cache_from:
      - ${NGINX_IMAGE:-iw/nginx}
      - ${PHP_IMAGE:-iw/php}
  - &node-cache-from
    cache_from:
      - ${NODE_IMAGE:-iw/node}

services:

  db:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - '5432:5432'
    networks: # I'm not sure about this
      - dev

  php:
    image: ${PHP_IMAGE:-iw/php}
    depends_on:
      - db
    build:
      context: ./app
      target: app_php
      <<: *app-cache-from
    volumes:
      - ./app:/srv/app:rw
      - ./app/docker/php/conf.d/api-platform.dev.ini/:/usr/local/etc/php/conf.d/api-platform.ini
      #- app-front:/srv/app/public/build
      - app-sf-cache:/srv/app/var
    networks: # I'm not sure about this
      - dev

  node:
    image: ${NODE_IMAGE:-iw/node}
    build:
      context: ./app
      dockerfile: Dockerfile.node
      <<: *node-cache-from
    command: sh -c "yarn install; yarn watch"
    working_dir: /home/node/app
    depends_on:
      - php
    volumes:
      - ./app:/home/node/app

  nginx:
    image: ${NGINX_IMAGE:-iw/nginx}
    build:
      context: ./app
      target: app_nginx
      <<: *app-cache-from
    depends_on:
      - php
      - node
    volumes:
      - ./app/public:/srv/app/public:ro
      #- app-front:/srv/app/public/build:ro
    ports:
      - "8082:80"
    networks: # I'm not sure about this
      - dev

# code taken from: https://blackfire.io/docs/up-and-running/docker
  blackfire:
    image: blackfire/blackfire:2
    ports: ["8307"]
    environment:
      # Exposes BLACKFIRE_* environment variables from the host
      BLACKFIRE_LOG_LEVEL: 4
      BLACKFIRE_SERVER_ID: $BLACKFIRE_SERVER_ID
      BLACKFIRE_SERVER_TOKEN: $BLACKFIRE_SERVER_TOKEN
      BLACKFIRE_CLIENT_ID: $BLACKFIRE_CLIENT_ID
      BLACKFIRE_CLIENT_TOKEN: $BLACKFIRE_CLIENT_TOKEN
    networks: # I'm not sure about this, but I saw in this tutorial: https://www.youtube.com/watch?v=aiDo9Ku93ew&ab_channel=YoanDev
      - dev

networks: # I'm not sure about this
  dev:

volumes:
  db-data: {}
  app-sf-cache: {}
  app-front: {}
